### ISSUE TITLE
fiff_read_events.m can't load events?

### ISSUE THREAD

**Issue by zuxfoucault** [mne-tools/mne-matlab#11]
I try to read events from MNE-sample-data. The events can be loaded in MNE-Python version. However, with the same data set the error message "Could not find events"  was printed in Matlab version.

<pre><code>
fname = 'sample_audvis_filt-0-40_raw.fif';
[events, mappings] = fiff_read_events(fname);
</pre></code>

Both line 38 and 52 in fiff_read_events.m, it seems that the FIFF predefined constants are not match to the data?

**Comment by agramfort** [comment]
fiff_read_events.m is meant to read -eve.fif files not from raw files that
contain the stim channel from which you still have to extract the events.

**Comment by zuxfoucault** [comment]
Thank you!
It works for -eve.fif files!
If I want to extract the events from -raw.fif, how can I read all the contents out?
(and then I can extract the events)

**Comment by agramfort** [comment]
not with matlab but with python and the http://martinos.org/mne/stable/generated/mne.find_events.html function.
