### ISSUE TITLE
.fif epochs import to Fieldtrip fails 

### ISSUE THREAD

**Issue by orekhova** [mne-tools/mne-matlab#12]
Hello, 
CC @robertoostenveld, @agramfort 

This is MNE-Fieldtrip format compatibility issue.

I tried to import  -epo.fif  file created in MNE python, latest version on today (v13)  using fieldtrip cookbook:

%%%%%%%%%%%%%%%%%%%%%%%
fiff_file = '/MYPATH/myfile-epo.fif';
cfg = []
cfg.dataset = fiff_file;
data1 = ft_preprocessing(cfg);
%%%%%%%%%%%%%%%%%%%%%%%

I got en error: 
Reference to non-existent field 'FIFFB_EPOCHS'.

Error using fiff_read_epochs (line 46)
Could not find epochs data

Error in fiff_read_epochs (line 46)
    error(me,'Could not find epochs data');

Error in ft_read_header (line 1665)
        epochs = fiff_read_epochs(filename);

Error in ft_preprocessing (line 397)
 hdr = ft_read_header(cfg.headerfile, 'headerformat', cfg.headerformat, 'coordsys', cfg.coordsys, 'coilaccuracy', cfg.coilaccuracy);

I use the latest  Fieldtrip version  fieldtrip-lite-20161024. It seems that something is wrong with the data structure...?

Elena Orekhova

**Comment by robertoostenveld** [comment]
the code around line 46 in fiff_read_epochs reads 

````
%
% Locate the data of interest
%
processed = fiff_dir_tree_find(meas, FIFF.FIFFB_PROCESSED_DATA);
if length(processed) == 0
        fclose(fid);
    error(me,'Could not find epochs data');
end

ep = fiff_dir_tree_find(meas, FIFF.FIFFB_EPOCHS);
if length(ep) == 0
        fclose(fid);
    error(me,'Could not find epochs data');  % LINE 46
end
````

It seems to me that 
1) the file was written incorrectly, or that 
2) the file does not contain any epochs, perhaps not even MEG data.

error 2 would be your error (i.e. trying to read the wrong file), error 1 would be an error in the writing code, i.e. in MNE-Python.

**Comment by robertoostenveld** [comment]
Perhaps you should report it as mne-python issue instead.
@agramfort, what do you think?

**Comment by orekhova** [comment]
I am sure that my -epo.fif file is OK, since I can browse it in  mne-python
and the epochs look  as they should.  I also used these epochs  for source
localization in MNE.
Therefore, it is more likely to be error [1]

Elena

**Comment by agramfort** [comment]
elena, can you share the epo.fif file?

**Comment by orekhova** [comment]
OK, but I can only do it tomorrow morning.
Elena

**Comment by orekhova** [comment]
Hi,
Here is the -epo.fif file I was not able to upload to the Fieldtrip.

https://drive.google.com/open?id=0B4vg0ZrqLpGCcnNBODBHSmJFcWM

Best regards,
Elena

**Comment by agramfort** [comment]
I think i fixed it in:

https://github.com/mne-tools/mne-matlab/commit/89a8b65e3126199c120c22ebfacc7c08de3f779d

if you confirm it works I'll open a PR on fieldtrip.

it's our mess with change/fix of FIFF constants.

**Comment by orekhova** [comment]
Dear Alex,

How can I try the fixed program? Should I download the new MNE version?

Elena

**Comment by agramfort** [comment]
just get the latest mne-matlab toolbox at:

https://github.com/mne-tools/mne-matlab/archive/master.zip

**Comment by orekhova** [comment]
Thank you!
It worked.

Elena

**Comment by agramfort** [comment]
see https://github.com/fieldtrip/fieldtrip/pull/250

closing.
