### ISSUE TITLE
Unable to load raw fif file 

### ISSUE THREAD

**Issue by Hui-Ling** [mne-tools/mne-matlab#19]
Hi MNE-matlab team,

Thanks for providing us this useful tools! 

Recently I tried to read fif raw file via Brainstorm and got some error messages (as shown below). The message may indicate that the function in MNE-matlab "fiff_read_meas_info" called by in_fopen_fif.m may not read all required information from my fif files. Also, I got the same error message when I tried to read those fif files that I have ever successfully imported 6 month ago. 

** Error: Line 131: Reference to non-existent field 'meas_date'.
**
** Call stack:
** >in_fopen_fif.m at 131
** >in_fopen.m at 68
** >import_raw.m at 126
** >bst_call.m at 28
** >tree_callbacks.m>@(h,ev)bst_call(@import_raw,[],[],iSubject) at 636

The following link can download a emptyroom fif file that was recorded. (Sorry. Because of the privacy issue, I could only provide the emptyroom data.)   
https://drive.google.com/file/d/13MmoEk58t87w85_3PPF4-Hy_AeWL1gLa/view?usp=sharing

Could you please help me to figure out whether I did anything wrong? 

Thank you very much!

Best,
Ling

**Comment by ftadel** [comment]
Ooops... this is a bug that was introduced in April only on the Brainstorm side, and luckily not reported here (https://github.com/brainstorm-tools/brainstorm3/commit/52c070479558b12c5dc2f3de90d32aa4cfcfa6c5)...
We've fixed it, and will open a PR to report these modifications here.
You can close this issue for now.

@juangpc 
Can you please make sure the two copies get synchronized correctly?
